# Generated by Django 6.0.4 on 2026-05-09 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('web', 'Web Technologies'), ('database', 'Database'), ('framework', 'Frameworks & Libraries'), ('cloud', 'Cloud & DevOps'), ('data_science', 'Data Science & AI'), ('tools', 'Tools & Software'), ('soft', 'Soft Skills')], default='programming', max_length=50)),
                ('icon', models.CharField(default='fa-code', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher (0-1 years)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (5+ years)')], default='fresher', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('salary_min', models.IntegerField(default=300000)),
                ('salary_max', models.IntegerField(default=800000)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('apply_link', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='talentfinder.company')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='talentfinder.skill')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('experience_years', models.FloatField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('candidate_email', models.CharField(blank=True, max_length=200)),
                ('candidate_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
                ('detected_skills', models.ManyToManyField(blank=True, related_name='resumes', to='talentfinder.skill')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0.0)),
                ('missing_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentfinder.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='talentfinder.resume')),
                ('matched_skills', models.ManyToManyField(blank=True, related_name='job_matches', to='talentfinder.skill')),
            ],
            options={
                'ordering': ['-match_percentage'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('preferred_job_type', models.CharField(blank=True, max_length=20)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
